table vw_fefo
	lineageTag: ddcf8314-e111-4c21-adc6-58fd8aba89fe

	measure m_valor_vendido = SUM(vw_fefo[valor])
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 50cedadd-51bc-4d74-b99f-5ee6f8e4271f

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure m_qtd_vendida = SUM(vw_fefo[qtd_consumida])
		formatString: 0
		lineageTag: b3d7d6fb-bdb9-4b66-b614-98208e4784ae

	measure m_tm =
			DIVIDE(
			    SUM(vw_fefo[valor]),
			    DISTINCTCOUNT(vw_fefo[id_saida])
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 806f7920-2cc0-4c25-bbf9-aef96d5e4f33

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column id_saida
		dataType: int64
		formatString: 0
		lineageTag: 6a1de9b9-ef64-40cc-b39c-981db2486af8
		summarizeBy: sum
		sourceColumn: id_saida

		annotation SummarizationSetBy = Automatic

	column id_cliente
		dataType: int64
		formatString: 0
		lineageTag: 8262104e-aaa7-42d6-9458-c08cea784ede
		summarizeBy: none
		sourceColumn: id_cliente

		annotation SummarizationSetBy = Automatic

	column id_local
		dataType: int64
		formatString: 0
		lineageTag: 4d990290-02b0-496a-854f-56ce06e87d65
		summarizeBy: none
		sourceColumn: id_local

		annotation SummarizationSetBy = Automatic

	column id_lote
		dataType: int64
		formatString: 0
		lineageTag: 00b97906-c408-4c1c-ad59-3d1395747119
		summarizeBy: none
		sourceColumn: id_lote

		annotation SummarizationSetBy = Automatic

	column qtd_consumida
		dataType: double
		lineageTag: 2ffd1dbe-2928-4abd-bacc-4377aefbba78
		summarizeBy: sum
		sourceColumn: qtd_consumida

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column valor
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 80eaee8b-6028-46d9-844f-599e8814f2d7
		summarizeBy: sum
		sourceColumn: valor

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column datahora_venda
		dataType: dateTime
		formatString: General Date
		lineageTag: 632a579c-7cb4-4dd5-9b49-5d5484cbaf93
		summarizeBy: none
		sourceColumn: datahora_venda

		variation Variation
			isDefault
			relationship: f1432760-9789-404f-bd10-a3d6ed16e629
			defaultHierarchy: LocalDateTable_fe15d71f-f4ee-4f6c-873f-1a2541d5668d.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_venda
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: a6a92d14-22ed-4afa-9799-6e1ae35dbbe3
		summarizeBy: none
		sourceColumn: data_venda

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column valor_unitario
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 28289bd7-d05e-4d37-bdcb-42bebddae11f
		summarizeBy: none
		sourceColumn: valor_unitario

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column nf
		dataType: string
		lineageTag: 7bad034a-e6b3-4984-a1cd-1f7905b1647f
		summarizeBy: none
		sourceColumn: nf

		annotation SummarizationSetBy = Automatic

	partition vw_fefo = m
		mode: import
		source =
				let
				    Fonte = Parquet.Document(File.Contents("C:\Users\mathe\repos\case-bi-duckdb\data\gold\vw_fefo.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null]),
				    #"Colunas Renomeadas" = Table.RenameColumns(Fonte,{{"custo_total", "valor"}})
				in
				    #"Colunas Renomeadas"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

