table vw_lote
	lineageTag: 554a5edd-cd69-4b6f-bbbf-3289c45fe69a

	measure m_qtd_entrada =
			CALCULATE(
			    SUM(vw_lote[quantidade_entrada]),
			    USERELATIONSHIP(vw_lote[data_recebimento], d_calendar[Date])
			)
		formatString: 0
		lineageTag: 7e4e3611-1f5e-4921-ab25-4d4f17973552

	measure m_valor_entrada =
			CALCULATE(
			    SUM(vw_lote[valor_entrada]),
			    USERELATIONSHIP(vw_lote[data_recebimento], d_calendar[Date])
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: f6ce2838-30c0-4d96-b1c1-ffd9f70f5f5b

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure m_qtd_expirada =
			
			CALCULATE(
			    SUM(vw_lote[quantidade_expirada]),
			    USERELATIONSHIP(vw_lote[data_vencimento], d_calendar[Date]),
			    NOT ISBLANK(vw_lote[data_vencimento]),
			    vw_lote[data_vencimento] <= TODAY()
			)
		formatString: 0
		lineageTag: 4fbf231d-56e4-4d65-a8fc-e1bffb746480

	measure m_valor_expirado =
			
			CALCULATE(
			    SUM(vw_lote[valor_expirado]),
			    USERELATIONSHIP(vw_lote[data_vencimento], d_calendar[Date])
			)
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: e42b144e-f4b8-47f9-958f-60ee12028b3d

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure m_valor_estoque = [m_valor_entrada] - [m_valor_vendido] - [m_valor_expirado]
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 0dd7eae0-7a77-4093-9c53-b1b8b41afa14

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	measure m_qtd_estoque = [m_qtd_entrada] - [m_qtd_expirada] - [m_qtd_vendida]
		formatString: 0
		lineageTag: 61e50da7-5992-4853-9c3d-d3901f42530e

	column id_lote
		dataType: int64
		formatString: 0
		lineageTag: 09fefdb3-e8df-4d80-a3ef-7f2adb57ffe8
		summarizeBy: none
		sourceColumn: id_lote

		annotation SummarizationSetBy = Automatic

	column id_sku
		dataType: int64
		formatString: 0
		lineageTag: b41607c5-e8e0-4620-8ae2-8e8b89c091d1
		summarizeBy: none
		sourceColumn: id_sku

		annotation SummarizationSetBy = Automatic

	column id_fornecedor
		dataType: int64
		formatString: 0
		lineageTag: 5d50ff02-9ac7-4b37-b3bb-d3c11e6bc155
		summarizeBy: none
		sourceColumn: id_fornecedor

		annotation SummarizationSetBy = Automatic

	column valor_unitario
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: f9df6b42-d79e-4e8d-8260-570af45707db
		summarizeBy: sum
		sourceColumn: valor_unitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column quantidade_entrada
		dataType: int64
		formatString: 0
		lineageTag: 9bae5b60-41d2-41ab-bb0a-9f7ca10e2e42
		summarizeBy: sum
		sourceColumn: quantidade_entrada

		annotation SummarizationSetBy = Automatic

	column quantidade_vendida
		dataType: double
		lineageTag: afd2d8f1-711f-44dd-be12-b03a92e7ba8f
		summarizeBy: sum
		sourceColumn: quantidade_vendida

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column valor_vendido
		dataType: double
		lineageTag: 5fab8428-10fd-4bb8-8ebb-d14bf5e2490e
		summarizeBy: sum
		sourceColumn: valor_vendido

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column quantidade_expirada
		dataType: double
		lineageTag: 596aa243-3dec-408f-964a-ceb791628af5
		summarizeBy: sum
		sourceColumn: quantidade_expirada

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column valor_expirado
		dataType: double
		lineageTag: 694ec7a6-57d1-4b40-8a78-cc9b1d90011b
		summarizeBy: sum
		sourceColumn: valor_expirado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column status
		dataType: string
		lineageTag: 51d9d498-544d-4930-b204-763c5742321d
		summarizeBy: none
		sourceColumn: status

		annotation SummarizationSetBy = Automatic

	column datahora_recebimento
		dataType: dateTime
		formatString: General Date
		lineageTag: c446471c-872b-404e-b3f7-f0c46babfde9
		summarizeBy: none
		sourceColumn: datahora_recebimento

		variation Variation
			isDefault
			relationship: 32492319-086e-4bc4-8973-651d4c96dde1
			defaultHierarchy: LocalDateTable_05c4c330-f23d-4e21-b5d5-3815a2b77ef6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

	column data_recebimento
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 07200418-b8d7-4ac0-a937-2a019df6ecf3
		summarizeBy: none
		sourceColumn: data_recebimento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column data_vencimento
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 42af5c8a-c881-4715-bb40-2c16fa260f69
		summarizeBy: none
		sourceColumn: data_vencimento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column nf
		dataType: string
		lineageTag: 312dee1a-32a3-4466-aa20-d7f46b2e360d
		summarizeBy: none
		sourceColumn: nf

		annotation SummarizationSetBy = Automatic

	column valor_entrada = vw_lote[quantidade_entrada] * vw_lote[valor_unitario]
		lineageTag: a70c8ee2-653f-4a32-93ea-5e60fcb04012
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition vw_lote = m
		mode: import
		source =
				let
				    Fonte = Parquet.Document(File.Contents("C:\Users\mathe\repos\case-bi-duckdb\data\gold\vw_lote.parquet"), [Compression=null, LegacyColumnNameEncoding=false, MaxDepth=null])
				in
				    Fonte

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

